name: rich_text_controller
description: An extended text editing controller that supports different inline styles for custom regex patterns
version: 1.4.2
homepage: https://github.com/micazi/rich_text_controller

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^5.3.2
  flutter_test:
    sdk: flutter

flutter:
